### ISSUE TITLE
Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit"

### ISSUE THREAD

**Issue by vkvashistha** [fingerprintjs/fingerprintjs-pro-ios#14]
Following is my FingerprintJS code to get visitorId:
`import UIKit
import FingerprintJSPro

class ViewController: UIViewController {

    let userActivityTracker = UserActivityTracker()
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        let token = "xxxxx"
        FingerprintJSProFactory
            .getInstance(
                token: token,
                endpoint: nil, // optional
                region: nil // optional
            )
            .getVisitorId { result in
                switch result {
                case let .failure(error):
                    print("Error: ", error.localizedDescription)
                case let .success(visitorId):
                    print("Success: ", visitorId)
                }
            }
    }

    
    @IBAction func onClicked(_ sender: Any) {
        print("Button clicked from ViewController")
    }
    
}`

This is the only ViewController (blank screen). After running the project I got following errors in my console:-
**Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}**

I'm running Xcode 13, UIKit framework with Swift 5

**Comment by petrpalata** [comment]
From what I can tell, the assertion/error is related to the RunningBoard daemon, which is an internal process that we don't have any power over. The entitlement the error refers to is Apple-only so adding it manually wouldn't fix it.

Besides the error, do you actually receive the success/error callback or does the call just hang indefinitely?

What's the environment you're running this in? Physical device? Simulator? Mac Catalyst?

**Comment by vkvashistha** [comment]
I'm running code on Simulator. OS : Monterey. targetting only iPhone
