### ISSUE TITLE
Xcode preview stopped working

### ISSUE THREAD

**Issue by adrianorezena** [fingerprintjs/fingerprintjs-pro-ios#19]
I'm having trouble with the SwiftUI Preview in Xcode 14.
I have the same problem with the Example.

```
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x0000600038a5a100):'FingerprintPro'>)
```

Does anyone have any idea what it could be?

**Comment by mgutski** [comment]
Closing as this does not seem to be an issue anymore.
